### ISSUE TITLE
AE_RL_NSL_KDD error

### ISSUE THREAD

**Issue by Light-City** [gcamfer/Anomaly-ReactionRL#14]
hello guys,I am very grateful to your open source code, why would you report the following error?
```
-------------------------------------------------------------------------------
Total epoch: 100 | Iterations in epoch: 100| Minibatch from mem size: 100 | Total Samples: 10000|
-------------------------------------------------------------------------------
Dataset shape: (125973, 162)
-------------------------------------------------------------------------------
Attacker parameters: Num_actions=23 | gamma=0.001 | epsilon=1 | ANN hidden size=100 | ANN hidden layers=1|
-------------------------------------------------------------------------------
Defense parameters: Num_actions=5 | gamma=0.001 | epsilon=1 | ANN hidden size=100 | ANN hidden layers=3|
-------------------------------------------------------------------------------

|Epoch 000/100| time: 1.98|
|Def Loss 0.0000 | Def Reward in ep 021|
|Att Loss 0.0000 | Att Reward in ep 079|
|Def Estimated: [14 15 22 29 20]| Att Labels: [ 4 17 24 40 15]
Traceback (most recent call last):
  File "/home/light/PycharmProjects/Anomaly-ReactionRL-master/Notebooks/AE_RL_NSL_KDD.py", line 804, in <module>
    defender_actions = defender_agent.act(states)
  File "/home/light/PycharmProjects/Anomaly-ReactionRL-master/Notebooks/AE_RL_NSL_KDD.py", line 526, in act
    actions = self.policy.get_actions(states)
  File "/home/light/PycharmProjects/Anomaly-ReactionRL-master/Notebooks/AE_RL_NSL_KDD.py", line 361, in get_actions
    self.Q = self.estimator.predict(states,states.shape[0])
  File "/home/light/PycharmProjects/Anomaly-ReactionRL-master/Notebooks/AE_RL_NSL_KDD.py", line 303, in predict
    return self.model.predict(state,batch_size=batch_size)
  File "/home/light/anaconda3/lib/python3.6/site-packages/keras/models.py", line 913, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/home/light/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1713, in predict
    verbose=verbose, steps=steps)
  File "/home/light/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1268, in _predict_loop
    ins_batch = _slice_arrays(ins, batch_ids)
  File "/home/light/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 406, in _slice_arrays
    return [None if x is None else x[start] for x in arrays]
  File "/home/light/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 406, in <listcomp>
    return [None if x is None else x[start] for x in arrays]
  File "/home/light/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2934, in __getitem__
    raise_missing=True)
  File "/home/light/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/home/light/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/home/light/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1246, in _validate_read_indexer
    key=key, axis=self.obj._get_axis_name(axis)))
KeyError: "None of [Int64Index([0], dtype='int64')] are in the [columns]"
```

**Comment by gcamfer** [comment]
Really sorry about the late response.
Can you please explain me more about the problem?
How can I reproduce the error.
Environment versions.
